feat: booking notifications
Iteam1337/predictivemovement pull request #237
Opened 2020-10-21 12:58 UTC by momentiris

Adds notifications for when a booking changes status.

2020-10-21 13:04 UTC, momentiris commented on packages/engine-server/lib/helpers.js
> +   * and the 'new' event.event.
```suggestion
   * and the 'new' event.status.
```

2020-10-21 13:06 UTC, momentiris commented on packages/engine-ui/src/components/Notification.tsx
> +  { notification: Notification } & { handleOnClose: (id: string) => void }
```suggestion
  { notification: Notification, handleOnClose: (id: string) => void }
```

2020-10-21 13:08 UTC, momentiris commented on packages/engine-ui/src/components/Notifications.tsx
> +    [BookingStatus.DELIVERY_FAILED]: 'Bokning  kunde inte levereras:',
```suggestion
    [BookingStatus.DELIVERY_FAILED]: 'En bokning kunde inte levereras:',
```

2020-10-21 13:12 UTC, momentiris commented on packages/engine-ui/src/utils/helpers.ts
> +const getLastFourChars = (str: string): string =>
```suggestion
const getLastFourChars = (str: string) =>
```

2020-10-26 10:30 UTC, lundeeell approved these changes
Nice! Just remove accepted from statuses as it just spams :)

2020-10-26 10:37 UTC, lundeeell requested changes
duplicate queue name

2020-10-26 13:04 UTC, lundeeell approved these changes
👍

2020-10-26 13:26 UTC, merged